[from here https://www.datacamp.com/community/tutorials/r-tutorial-apply-family?utm_source=adwords_ppc&utm_campaignid=898687156&utm_adgroupid=48947256715&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=1t1&utm_creative=229765585186&utm_targetid=aud-299261629574:dsa-473406586995&utm_loc_interest_ms=&utm_loc_physical_ms=1006976&gclid=CjwKCAjwh9_bBRA_EiwApObaOBBBa3VQg2IdUyVeeI0gMPTVevVK_LBKtyEp6hDeKp0sWCwjgMKLORoCV2MQAvD_BwE#codelapplycode]

These functions allow crossing the data in a number of ways and avoid explicit use of loop constructs. They act on an input list, matrix or array and apply a named function with one or several optional arguments.

#### apply()

In [1]:
X <- matrix(rnorm(30), nrow=5, ncol=6)

In [2]:
X

[,1]       [,2]       [,3]       [,4]       [,5]        [,6]      
[1,] -1.7648698 -0.9681232  0.8652812 -1.3385158  0.15191537 -0.7293546
[2,] -0.2429392  0.1016771  0.2233147  0.8072886 -0.04300274 -0.7057317
[3,] -1.1247899  0.1935240 -0.3702220 -0.9269893 -0.37576651  1.3872886
[4,]  0.7997437  0.3726808 -0.5780711 -0.7692512 -0.36780100 -1.3405953
[5,]  0.5810471 -0.1703864  1.5247963 -1.0809034 -0.15817830 -0.9181016

In [3]:
apply(X, 2, sum)

[1] -1.7518082 -0.4706278  1.6650990 -3.3083710 -0.7928332 -2.3064946

#### lapply()

The difference from apply() is that:

- It can be used for other objects like dataframes, lists or vectors; and
- The output returned is a list (which explains the “l” in the function name), which has the same number of elements as the object passed to it.

In [4]:
A <- matrix(data = 1:9, nrow = 3, ncol = 3)
B <- matrix(data = 4:15, nrow = 4, ncol = 3)
C <- matrix(data = 8:10, nrow = 3, ncol = 2)

MyList <- list(A, B, C)

In [5]:
MyList

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

The empty space between the commas is because that's because where you'd say what row we want; 
here, we only want column

In [6]:
lapply(MyList,"[", ,2)

[[1]]
[1] 4 5 6

[[2]]
[1]  8  9 10 11

[[3]]
[1]  8  9 10

In this case we have selected a row, but we've left the column blank

In [7]:
lapply(MyList, "[", 1, )

[[1]]
[1] 1 4 7

[[2]]
[1]  4  8 12

[[3]]
[1] 8 8

#### sapply()

The sapply() function works like lapply(), but it tries to simplify the output to the most elementary data structure that is possible. And indeed, sapply() is a ‘wrapper’ function for lapply().

In [8]:
# Compare lapply() and sapply()

lapply(MyList,"[", 2, 1 )

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

In [9]:
typeof(lapply(MyList,"[", 2, 1 ))

[1] "list"

In [10]:
sapply(MyList, "[", 2, 1)

[1] 2 5 9

In [11]:
typeof(sapply(MyList, "[", 2, 1))

[1] "integer"

In [12]:
# When simplify is FALSE behavious is as with lapply()

sapply(MyList, "[", 2, 1, simplify = FALSE)

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

Good article: https://www.r-bloggers.com/using-apply-sapply-lapply-in-r/. Implemented below:

In [13]:
m <- matrix(data=cbind(rnorm(30, 0), rnorm(30, 2), rnorm(30, 5)), nrow=30, ncol=3)

In [14]:
m

[,1]        [,2]       [,3]    
 [1,]  0.71279691 1.51749294 4.113684
 [2,] -0.81720056 1.63225061 4.208022
 [3,]  0.46750026 0.49209897 4.485332
 [4,]  0.71779986 2.06275902 4.970641
 [5,]  1.17039595 3.03498602 5.206474
 [6,] -1.32376309 0.01582787 3.653192
 [7,]  0.45623360 1.97765534 5.888694
 [8,]  0.06133481 2.31621796 3.933522
 [9,] -0.92513310 3.79546636 5.644410
[10,]  0.04869757 2.88742681 4.862328
[11,] -0.46990818 3.00781731 4.617315
[12,] -0.81899668 1.87115483 5.068472
[13,] -0.71555208 0.75476431 5.452665
[14,]  2.13848156 2.11389198 5.677565
[15,]  0.10081462 2.23927145 5.093619
[16,] -0.34841425 0.98664426 4.115352
[17,]  0.74236139 3.77659246 4.989279
[18,] -0.18010497 0.72671900 7.086473
[19,] -0.82284605 1.61845811 6.172139
[20,]  0.92636448 0.47655912 6.024790
[21,] -0.14560437 1.61819898 4.056185
[22,] -1.94686707 2.56573751 2.928770
[23,] -0.44374362 1.68889650 4.721460
[24,] -0.32420776 1.78320106 3.104522
[25,] -0.93877949 1.70391621 4.469461
[26,] -0.66477503 1.50792751 7.067729
[27,] -0.68024846 1.85382201 3.635512
[28,]  0.73053034 0.86812486 4.687576
[29,] -2.24681493 0.88250009 5.806628
[30,]  1.90369045 1.46317656 4.849133

In [15]:
apply(m, 2, mean)

[1] -0.1211986  1.7746519  4.8863649

In [16]:
apply(m, 2, function(x) length(x[x<0]))

[1] 17  0  0

Here the function definition is not required, we could instead just pass the is.vector function, as it only takes one argument and has already been wrapped up in a function for us. Let’s check they are vectors as we might expect.

In [17]:
apply(m, 2, is.vector) == apply(m, 2, function(x) is.vector(x))

[1] TRUE TRUE TRUE

Why then did we need to wrap up our length function? When we want to define our own handling function for apply, we must at a minimum give a name to the incoming data, so we can use it in our function.

In [19]:
# This will break

apply(m, 2, length(x[x<0]))

ERROR: Error in match.fun(FUN): object 'x' not found


In [20]:
apply(m, 2, function(x) mean(x[x>0]))

[1] 0.7828463 1.7746519 4.8863649

Some of the other functions:

In [21]:
sapply(1:3, function(x) x^2)

[1] 1 4 9

In [22]:
lapply(1:3, function(x) x^2)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

In [23]:
sapply(1:3, function(x) x^2, simplify=F)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

In [24]:
unlist(lapply(1:3, function(x) x^2))

[1] 1 4 9

In [25]:
# This is apparently a vector

typeof(unlist(lapply(1:3, function(x) x^2)))

[1] "double"

#### In sum:

apply : used with matrices, and gives back matrices or vectors 

sapply : takes vectors, and gives back vectors

lapply : takes vectors/lists, and gives back a list

In [26]:
add2 <- function(x) {
    x + 2
}

In [27]:
v <- seq(1:10) 
lapply(X = v, FUN = add2)

[[1]]
[1] 3

[[2]]
[1] 4

[[3]]
[1] 5

[[4]]
[1] 6

[[5]]
[1] 7

[[6]]
[1] 8

[[7]]
[1] 9

[[8]]
[1] 10

[[9]]
[1] 11

[[10]]
[1] 12

In [28]:
m

[,1]        [,2]       [,3]    
 [1,]  0.71279691 1.51749294 4.113684
 [2,] -0.81720056 1.63225061 4.208022
 [3,]  0.46750026 0.49209897 4.485332
 [4,]  0.71779986 2.06275902 4.970641
 [5,]  1.17039595 3.03498602 5.206474
 [6,] -1.32376309 0.01582787 3.653192
 [7,]  0.45623360 1.97765534 5.888694
 [8,]  0.06133481 2.31621796 3.933522
 [9,] -0.92513310 3.79546636 5.644410
[10,]  0.04869757 2.88742681 4.862328
[11,] -0.46990818 3.00781731 4.617315
[12,] -0.81899668 1.87115483 5.068472
[13,] -0.71555208 0.75476431 5.452665
[14,]  2.13848156 2.11389198 5.677565
[15,]  0.10081462 2.23927145 5.093619
[16,] -0.34841425 0.98664426 4.115352
[17,]  0.74236139 3.77659246 4.989279
[18,] -0.18010497 0.72671900 7.086473
[19,] -0.82284605 1.61845811 6.172139
[20,]  0.92636448 0.47655912 6.024790
[21,] -0.14560437 1.61819898 4.056185
[22,] -1.94686707 2.56573751 2.928770
[23,] -0.44374362 1.68889650 4.721460
[24,] -0.32420776 1.78320106 3.104522
[25,] -0.93877949 1.70391621 4.469461
[26,] -0.66477503 1.50792751 7.067729
[27,] -0.68024846 1.85382201 3.635512
[28,]  0.73053034 0.86812486 4.687576
[29,] -2.24681493 0.88250009 5.806628
[30,]  1.90369045 1.46317656 4.849133

#### MARGIN
a vector giving the subscripts which the function will be applied over. E.g., for a matrix 1 indicates rows, 2 indicates columns, c(1, 2) indicates rows and columns. Where X has named dimnames, it can be a character vector selecting dimension names.

In [29]:
apply(X = m, MARGIN = c(1, 2), FUN = add2)

[,1]        [,2]     [,3]    
 [1,]  2.71279691 3.517493 6.113684
 [2,]  1.18279944 3.632251 6.208022
 [3,]  2.46750026 2.492099 6.485332
 [4,]  2.71779986 4.062759 6.970641
 [5,]  3.17039595 5.034986 7.206474
 [6,]  0.67623691 2.015828 5.653192
 [7,]  2.45623360 3.977655 7.888694
 [8,]  2.06133481 4.316218 5.933522
 [9,]  1.07486690 5.795466 7.644410
[10,]  2.04869757 4.887427 6.862328
[11,]  1.53009182 5.007817 6.617315
[12,]  1.18100332 3.871155 7.068472
[13,]  1.28444792 2.754764 7.452665
[14,]  4.13848156 4.113892 7.677565
[15,]  2.10081462 4.239271 7.093619
[16,]  1.65158575 2.986644 6.115352
[17,]  2.74236139 5.776592 6.989279
[18,]  1.81989503 2.726719 9.086473
[19,]  1.17715395 3.618458 8.172139
[20,]  2.92636448 2.476559 8.024790
[21,]  1.85439563 3.618199 6.056185
[22,]  0.05313293 4.565738 4.928770
[23,]  1.55625638 3.688897 6.721460
[24,]  1.67579224 3.783201 5.104522
[25,]  1.06122051 3.703916 6.469461
[26,]  1.33522497 3.507928 9.067729
[27,]  1.31975154 3.853822 5.635512
[28,]  2.73053034 2.868125 6.687576
[29,] -0.24681493 2.882500 7.806628
[30,]  3.90369045 3.463177 6.849133

#### Playing with strings..

In [37]:
str1 <- "hey"
str2 <- "yo"
str3 <- "pal"

In [38]:
paste(str1, str2, sep = "")

[1] "heyyo"

In [39]:
paste0(str1, str2, str3)

[1] "heyyopal"

In [40]:
library(stringr)

In [42]:
names <- c("Rossi", "John", "Sarah", "Celia")

In [43]:
str_sub(names, start = 3, end = 3)

[1] "s" "h" "r" "l"