These functions allow crossing the data in a number of ways and avoid explicit use of loop constructs. They act on an input list, matrix or array and apply a named function with one or several optional arguments.

#### apply()

In [6]:
X <- matrix(rnorm(30), nrow=5, ncol=6)

In [7]:
X

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,]  0.4029070 -0.6111580 -0.1110993 1.03861071  0.6337987  0.8128393
[2,] -1.6106310 -1.6155476 -0.6415986 0.70871958  0.8617486  0.4706307
[3,] -0.5733615  1.4025059 -2.0458345 0.33162131 -0.2783490 -0.2866901
[4,] -0.4463302 -1.8855719  0.4015227 0.08360631  0.1910340 -1.1606639
[5,] -2.1239840 -0.9275915  0.3034109 0.07017375  1.3278561 -0.2229517

In [8]:
apply(X, 2, sum)

[1] -4.3513998 -3.6373631 -2.0935988  2.2327317  2.7360885 -0.3868358

#### lapply()

The difference from apply() is that:

- It can be used for other objects like dataframes, lists or vectors; and
- The output returned is a list (which explains the “l” in the function name), which has the same number of elements as the object passed to it.

In [23]:
A <- matrix(data = 1:9, nrow = 3, ncol = 3)
B <- matrix(data = 4:15, nrow = 4, ncol = 3)
C <- matrix(data = 8:10, nrow = 3, ncol = 2)

MyList <- list(A, B, C)

In [26]:
MyList

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

The empty space between the commas is because that's because where you'd say what row we want; 
here, we only want column

In [42]:
lapply(MyList,"[", ,2)

[[1]]
[1] 4 5 6

[[2]]
[1]  8  9 10 11

[[3]]
[1]  8  9 10

In this case we have selected a row, but we've left the column blank

In [43]:
lapply(MyList, "[", 1, )

[[1]]
[1] 1 4 7

[[2]]
[1]  4  8 12

[[3]]
[1] 8 8